name: 'dbt_demo'
profile: 'dbt_demo'


model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"

models:
  dbt_demo:
    staging:
      +database: stg
      +schema: airbnb
      +materialized: ephemeral
    integration:
      +database: int
      +schema: airbnb
      +materialized: table

seeds:
  dbt_demo:
    +database: int
    +schema: airbnb